title: Rangoli
logo: /assets/img/rangoli.svg
description: Free, Open Source, Lightweight, Cross-platform Software for Royal Kludge Keyboards
theme: jekyll-theme-minimal

repository_url: https://github.com/rnayabed/rangoli
repository_name: rnayabed/rangoli
owner_url: https://github.com/rnayabed
owner_name: Debayan Sutradhar
logo_url: https://twitter.com/Sab_gfx
logo_name: Sab GFX

donate_url: https://ko-fi.com/rnayabed
base_url: https://rnayabed.github.io/rangoli_website